version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: x64
environment:
  BOOST_HOME: C:\Libraries\boost_1_67_0
  BOOST_LIB_PATH: C:\Libraries\boost_1_67_0\lib64-msvc-14.1
before_build:
- cmd: set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;%PATH%
build:
  project: Hypodermic.sln
  verbosity: normal